services:
  web:
    build: .
    container_name: metroapp_web
    command: gunicorn metroapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    
  nginx:
    image: nginx:1.29.3
    container_name: metroapp_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certificates:/etc/letsencrypt
      - ./static:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

  db:
    image: postgres:17
    container_name: metroapp_db
    restart: always
    environment:
      POSTGRES_DB: metrodb
      POSTGRES_USER: metrouser
      POSTGRES_PASSWORD: metropass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
