services:
  web:
    build: .
    container_name: metroapp_web
    command: gunicorn metroapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db
  
  certbot:
    image: certbot/certbot
    container_name: metroapp_certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM;
             while :; do
               certbot renew;
               sleep 12h;
             done"
  nginx:
    image: nginx:1.29.3
    container_name: metroapp_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot_www:/var/www/certbot
      - certbot_certs:/etc/letsencrypt
      - ./static:/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  db:
    image: postgres:17
    container_name: metroapp_db
    restart: always
    environment:
      POSTGRES_DB: metrodb
      POSTGRES_USER: metrouser
      POSTGRES_PASSWORD: metropass
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  certbot_www:
  certbot_certs:
